---
version: "3.7"

networks:
  traefik_proxy:
    name: traefik_proxy
    external: true

services:
  # This image requires some prior setup!
  auth:
    image: clems4ever/authelia:latest
    container_name: authelia
    restart: unless-stopped
    networks:
      - traefik_proxy
    depends_on:
      - auth_redis
      - auth_mongo
    volumes:
      # set up and add to directory: https://github.com/clems4ever/authelia/blob/master/config.template.yml
      - ${APPDATA_DIR}/authelia/config.yml:/etc/authelia/config.yml:ro
      - ${APPDATA_DIR}/authelia/users.yml:/etc/authelia/users.yml
    labels:
      traefik.enable: true
      traefik.docker.network: traefik_proxy
      traefik.backend: auth
      traefik.port: 9091
      traefik.frontend.rule: Host:auth.${ROOT_DOMAIN}

  auth_redis:
    image: redis:5.0.5-alpine
    container_name: auth_redis
    restart: unless-stopped
    networks:
      - traefik_network

  auth_mongo:
    image: mongo:latest
    container_name: auth_mongo
    restart: unless-stopped
    networks:
      - traefik_network
    environment:
      - MONGO_INITDB_DATABASE=authelia
    volumes:
      - ${STORAGE_DIR}/data/authelia_mongo:/data/db
